version: '2'
services:
  ddns:
    image: davd/docker-ddns:1.2.1
    restart: always
    environment:
      RECORD_TTL: 60
      ZONE: '${DOMAIN}'
      SHARED_SECRET: '${SHARED_SECRET}'
    ports:
      - "${DNS_PORT}:53"
      - "${DNS_PORT}:53/udp"
    volumes:
       - ./data/bind-data:/var/cache/bind
    networks:
      red:
  python:
    image: pyddns:3.0
    build: ./docker
    restart: always
    volumes:
      - ./appdata/pyddns:/usr/src/app
      - ./appdata/static/node_modules:/usr/src/app/static/node_modules
    environment:
      DNS_HOST: ddns
      DNS_API_PORT: 8080
      DNS_DOMAIN: '${DOMAIN}'
      DNS_SHARED_SECRET: '${SHARED_SECRET}'
      DNS_ALLOW_AGENT: '${DNS_ALLOW_AGENT}'
      DB_HOST: postgres
      DB_NAME: '${DATABASE_NAME}'
      DB_USER: '${DATABASE_USER}'
      DB_PASSWORD: '${DATABASE_PASS}'
      DJANGO_ADMIN_URL: administrator
      DJANGO_SU_NAME: '${DJANGO_SU_NAME}'
      DJANGO_SU_EMAIL: '${DJANGO_SU_EMAIL}'
      DJANGO_SU_PASSWORD: '${DJANGO_SU_PASSWORD}'
      OWN_ADMIN: '${OWN_ADMIN}'
    depends_on:
      - "postgres"
    networks:
      red:

  postgres:
    image: postgres:9.6
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASS}
      POSTGRES_USER: '${DATABASE_NAME}'
      POSTGRES_DB: '${DATABASE_USER}'
    volumes:
     - ./data/dbdata:/var/lib/postgresql/data
    networks:
      red:

  nginx:
    image: nginx:latest
    ports:
      - "${WEB_PORT}:8000"
    volumes:
      - ./config/nginx_src:/src
      - ./config/nginx:/etc/nginx/conf.d
      - ./appdata/static:/static
    depends_on:
      - "python"
    networks:
      red:
networks:
  red:

